### ISSUE TITLE
Humidity randomly starts reading incorrectly

### ISSUE THREAD

**Issue by handsomedave** [sparkfun/SparkFun_BME280_Breakout_Board#4]
I have two ESP8266 Things with one each BME280 on each device. They are reading Temp/Humidity/Pressure with i2c and logging it to a web service. Randomly one of them will start reading about 50% higher than the other. If I power cycle the Thing it then reads correctly for a random amount of time before again reading incorrectly. It has started to read incorrectly in as little as 5 minutes or as much as 20 hours. I doesn't slowly start drifting away from a correct reading, it just all at once jumps 50% or so.

I have swapped sensors between devices and it seems to only occur with one of the Things regardless of which sensor is hooked up. Other than the two constants used to identify the specific device and sensor the code running on the Things is identical.

**Comment by santaimpersonator** [comment]
Based on your explanation of your issue, it sounds like it is an issue with the "ESP8266 Thing". I am closing out this GitHub issue since it doesn't sound like it is related to the BME280; feel free to re-open the issue if necessary. Otherwise, if you are looking for technical assistance, please create a post on our [forum](https://forum.sparkfun.com/).
